using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProcurementHTE.Core.Authorization;
using ProcurementHTE.Core.Enums;
using ProcurementHTE.Core.Models;
using ProcurementHTE.Web.Extensions;
using ProcurementHTE.Web.Models.ViewModels;
using ProcurementHTE.Web.Utils;

namespace ProcurementHTE.Web.Controllers.ProcurementModule;

public partial class ProcurementsController
{
    [HttpGet]
    [Authorize(Policy = Permissions.Procurement.Create)]
    public async Task<IActionResult> Create(
        string? jobTypeId = null,
        ProcurementCategory? category = null
    )
    {
        var viewModel = await BuildCreateViewModelAsync(jobTypeId, category);
        return View("CreateByType", viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = Permissions.Procurement.Create)]
    public async Task<IActionResult> Create(
        [FromForm] ProcurementCreateViewModel procurementViewModel,
        string submitAction
    )
    {
        _logger.LogDebug("Create procurement POST received with submit action {SubmitAction}", submitAction);
        RemoveAutoGeneratedProcurementValidation();
        RemoveDetailsValidation();
        RemoveOffersValidation();
        LogCreateModelState("after removing auto-generated validation");

        procurementViewModel.Procurement ??= new Procurement();
        procurementViewModel.Details ??= [];
        procurementViewModel.Offers ??= [];

        var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier)
            ?? throw new InvalidOperationException("User tidak terautentikasi");
        var proc = procurementViewModel.Procurement;
        proc.UserId = currentUserId;
        proc.PicOpsUserId = currentUserId;

        var isDraft = submitAction?.Equals("Draft", StringComparison.OrdinalIgnoreCase) == true;
        _logger.LogDebug("Create procurement request resolved draft mode: {IsDraft}", isDraft);

        var status = await _queryService.GetStatusByNameAsync(submitAction ?? "");
        if (status == null)
        {
            _logger.LogWarning("Create procurement failed because status {SubmitAction} was not found", submitAction);
            ModelState.AddModelError("", $"Status '{submitAction}' tidak ditemukan di database. Pastikan ada entry 'Draft' dan 'Created' di tabel Statuses.");
            await RepopulateCreateViewModel(procurementViewModel);
            return View("CreateByType", procurementViewModel);
        }
        proc.StatusId = status.StatusId;

        ValidateProcurementForm(procurementViewModel, isDraft);
        LogCreateModelState("after procurement form validation");
        if (!ModelState.IsValid)
        {
            _logger.LogDebug("Returning create procurement view due to validation errors");
            await RepopulateCreateViewModel(procurementViewModel);
            return View("CreateByType", procurementViewModel);
        }

        ApplyCreateDefaults(proc, currentUserId, isDraft);

        try
        {
            _logger.LogDebug(
                "Saving procurement. JobTypeId={JobTypeId}, StatusId={StatusId}, Offers={OfferCount}, Details={DetailCount}",
                proc.JobTypeId,
                proc.StatusId,
                procurementViewModel.Offers?.Count ?? 0,
                procurementViewModel.Details?.Count ?? 0
            );

            proc.SpmpNumber = ProcurementReferenceNumberFormatter.AppendSuffixIfNeeded(proc.SpmpNumber);
            proc.OeNumber = ProcurementReferenceNumberFormatter.AppendSuffixIfNeeded(proc.OeNumber);

            await _commandService.AddProcurementWithDetailsAsync(
                proc,
                procurementViewModel.Details ?? [],
                procurementViewModel.Offers ?? []
            );

            _logger.LogInformation(
                "Procurement created successfully. ProcurementId={ProcurementId}, IsDraft={IsDraft}",
                proc.ProcurementId,
                isDraft
            );

            TempData["SuccessMessage"] = isDraft
                ? "Procurement saved as draft successfully"
                : "Procurement created successfully";
            return RedirectToAction(nameof(Index));
        }
        catch (ArgumentException ex)
        {
            _logger.LogWarning(ex, "Create procurement validation failed");
            ModelState.AddModelError("", $"Validasi gagal: {ex.Message}");
        }
        catch (DbUpdateException ex)
        {
            _logger.LogError(ex, "Create procurement database save failed");
            ModelState.AddModelError("", $"Gagal menyimpan data ke database: {ex.InnerException?.Message ?? ex.Message}");
        }
        catch (InvalidOperationException ex)
        {
            _logger.LogWarning(ex, "Create procurement operation failed");
            ModelState.AddModelError("", $"Operasi tidak valid: {ex.Message}");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected failure while creating procurement");
            ModelState.AddModelError("", $"Terjadi kesalahan saat menyimpan data: {ex.Message}");
        }

        await RepopulateCreateViewModel(procurementViewModel);
        return View("CreateByType", procurementViewModel);
    }

    private void LogCreateModelState(string phase)
    {
        _logger.LogInvalidModelState(
            ModelState,
            "create procurement",
            phase,
            HttpContext.TraceIdentifier
        );
    }

    private static void ApplyCreateDefaults(Procurement proc, string currentUserId, bool isDraft)
    {
        if (string.IsNullOrWhiteSpace(proc.AnalystHteUserId))
            proc.AnalystHteUserId = currentUserId;
        if (string.IsNullOrWhiteSpace(proc.AssistantManagerUserId))
            proc.AssistantManagerUserId = currentUserId;
        if (string.IsNullOrWhiteSpace(proc.ManagerUserId))
            proc.ManagerUserId = currentUserId;
        if (string.IsNullOrWhiteSpace(proc.JobName))
            proc.JobName = isDraft ? "(Draft)" : proc.JobName;
    }
}
