using ProcurementHTE.Core.Enums;
using ProcurementHTE.Core.Models;
using ProcurementHTE.Web.Models.ViewModels;

namespace ProcurementHTE.Web.Controllers.ProcurementModule;

public partial class ProcurementsController
{
    private void ValidateProcurementForm(ProcurementCreateViewModel vm, bool isDraft)
    {
        var proc = vm.Procurement;
        var prefix = $"{nameof(vm.Procurement)}";

        if (string.IsNullOrWhiteSpace(proc.JobTypeId))
            ModelState.AddModelError($"{prefix}.{nameof(proc.JobTypeId)}", "Pilih job type terlebih dahulu");

        if (isDraft)
            return;

        if (proc.ContractType == 0)
            ModelState.AddModelError($"{prefix}.{nameof(proc.ContractType)}", "Contract type wajib dipilih");
        if (proc.ProcurementCategory == 0)
            ModelState.AddModelError($"{prefix}.{nameof(proc.ProcurementCategory)}", "Jenis pengadaan wajib dipilih");
        if (string.IsNullOrWhiteSpace(proc.JobName))
            ModelState.AddModelError($"{prefix}.{nameof(proc.JobName)}", "Nama pekerjaan wajib diisi");
        if (proc.DocumentDate == default)
            ModelState.AddModelError($"{prefix}.{nameof(proc.DocumentDate)}", "Tanggal dokumen wajib diisi");
        if (proc.StartDate == default)
            ModelState.AddModelError($"{prefix}.{nameof(proc.StartDate)}", "Tanggal mulai wajib diisi");
        if (proc.EndDate == default)
            ModelState.AddModelError($"{prefix}.{nameof(proc.EndDate)}", "Tanggal selesai wajib diisi");
        if (proc.StartDate != default && proc.EndDate != default && proc.EndDate < proc.StartDate)
            ModelState.AddModelError($"{prefix}.{nameof(proc.EndDate)}", "Tanggal selesai harus setelah tanggal mulai");
        if (proc.ProcurementCategory == ProcurementCategory.Jasa && string.IsNullOrWhiteSpace(proc.RaNumber))
            ModelState.AddModelError($"{prefix}.{nameof(proc.RaNumber)}", "RA Number wajib diisi untuk jenis pengadaan jasa");

        ValidateCreateOffers(vm);
    }

    private void ValidateCreateOffers(ProcurementCreateViewModel vm)
    {
        if (vm.Offers == null || vm.Offers.Count == 0)
        {
            ModelState.AddModelError(nameof(vm.Offers), "Minimal harus ada 1 item penawaran untuk membuat procurement");
            return;
        }

        var offerIndexes = Request.Form["Offers.Index"].ToArray();
        for (int i = 0; i < offerIndexes.Length; i++)
        {
            var idx = offerIndexes[i];
            var offer = vm.Offers.ElementAtOrDefault(i);
            if (offer == null)
                continue;

            if (string.IsNullOrWhiteSpace(offer.ItemPenawaran))
                ModelState.AddModelError($"Offers[{idx}].ItemPenawaran", "Item penawaran wajib diisi");
            if (offer.Qty <= 0)
                ModelState.AddModelError($"Offers[{idx}].Qty", "Qty harus lebih dari 0");
            if (string.IsNullOrWhiteSpace(offer.Unit))
                ModelState.AddModelError($"Offers[{idx}].Unit", "Unit wajib diisi");
        }
    }

    private void RemoveAutoGeneratedProcurementValidation()
    {
        var prefix = $"{nameof(ProcurementCreateViewModel.Procurement)}.";
        var fieldsToRemove = new[]
        {
            nameof(Procurement.ProcNum),
            nameof(Procurement.ProcurementId),
            nameof(Procurement.PicOpsUserId),
            nameof(Procurement.UserId),
            nameof(Procurement.CreatedAt),
            nameof(Procurement.ProcurementStatus),
            nameof(Procurement.DocumentDate),
            nameof(Procurement.StartDate),
            nameof(Procurement.EndDate),
            nameof(Procurement.ContractType),
            nameof(Procurement.ProcurementCategory),
            nameof(Procurement.ProjectRegion),
            nameof(Procurement.JobName),
            nameof(Procurement.JobTypeId),
            nameof(Procurement.AnalystHteUserId),
            nameof(Procurement.AssistantManagerUserId),
            nameof(Procurement.ManagerUserId),
            nameof(Procurement.Status),
            nameof(Procurement.JobType),
        };

        foreach (var field in fieldsToRemove)
            ModelState.Remove($"{prefix}{field}");

        ModelState.Remove(nameof(ProcurementCreateViewModel.Procurement));
    }

    private void RemoveDetailsValidation()
    {
        foreach (var key in Request.Form["Details.Index"].ToArray())
        {
            ModelState.Remove($"Details[{key}].ProcurementId");
            ModelState.Remove($"Details[{key}].Procurement");
            ModelState.Remove($"Details[{key}].ProcDetailId");
        }
    }

    private void RemoveOffersValidation()
    {
        foreach (var key in Request.Form["Offers.Index"].ToArray())
        {
            ModelState.Remove($"Offers[{key}].ProcurementId");
            ModelState.Remove($"Offers[{key}].Procurement");
            ModelState.Remove($"Offers[{key}].ProcOfferId");
            ModelState.Remove($"Offers[{key}].Qty");
            ModelState.Remove($"Offers[{key}].ItemPenawaran");
            ModelState.Remove($"Offers[{key}].Unit");
        }
    }
}
