// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcurementHTE.Infrastructure.Data;

#nullable disable

namespace ProcurementHTE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.DocumentApprovalRule", b =>
                {
                    b.Property<string>("DocumentApprovalRuleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApproverRoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApproverUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DocumentTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JobTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProcurementCategory")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SubmitterRoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitterUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DocumentApprovalRuleId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("SubmitterUserId");

                    b.HasIndex("DocumentTypeId", "JobTypeId", "ProcurementCategory", "MinAmount", "MaxAmount", "IsActive");

                    b.ToTable("DocumentApprovalRules");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.DocumentApprovals", b =>
                {
                    b.Property<string>("DocumentApprovalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobTypeDocumentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DocumentApprovalId");

                    b.HasIndex("JobTypeDocumentId");

                    b.HasIndex("RoleId");

                    b.ToTable("DocumentApprovals");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.DocumentType", b =>
                {
                    b.Property<string>("DocumentTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.JobTypeDocuments", b =>
                {
                    b.Property<string>("JobTypeDocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUploadRequired")
                        .HasColumnType("bit");

                    b.Property<string>("JobTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcurementCategory")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("JobTypeDocumentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobTypeDocuments");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.JobTypes", b =>
                {
                    b.Property<string>("JobTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NotificationType");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcDetail", b =>
                {
                    b.Property<string>("ProcDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DetailKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ItemName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VendorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProcDetailId");

                    b.HasIndex("ProcurementId");

                    b.HasIndex("VendorId");

                    b.ToTable("ProcDetails");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcDocuments", b =>
                {
                    b.Property<string>("ProcDocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("ProcDocumentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ProcurementId");

                    b.ToTable("ProcDocuments");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcOffer", b =>
                {
                    b.Property<string>("ProcOfferId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemPenawaran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitRevenue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcOfferId");

                    b.HasIndex("ProcurementId");

                    b.ToTable("ProcOffers");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Procurement", b =>
                {
                    b.Property<string>("ProcurementId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("AccrualFilledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccrualFilledByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AnalystHtePjs")
                        .HasColumnType("bit");

                    b.Property<string>("AnalystHteUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ApInvoicePickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApInvoiceUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppoUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalSentByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovalTokenGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArPickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AssistantManagerPjs")
                        .HasColumnType("bit");

                    b.Property<string>("AssistantManagerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HardcopyEvidenceContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HardcopyEvidenceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HardcopyEvidenceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("HardcopyEvidenceFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("HardcopySubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HardcopySubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IspaDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IspaFileContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IspaFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IspaFileObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("IspaFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("IspaNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("IspaSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IspaSubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IspaSubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LdpFileContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LdpFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LdpFileObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("LdpFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LdpUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LdpUploadedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LtcName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ManagerApprovalEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ManagerApprovalStartAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ManagerPjs")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoAccrual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoHte")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoRig")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OpDirApprovalEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OpDirApprovalStartAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OperationDirectorPjs")
                        .HasColumnType("bit");

                    b.Property<string>("OperationDirectorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PendingRevisionSymptoms")
                        .HasColumnType("int");

                    b.Property<string>("PicOpsUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PoSubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoSubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("PotensiAccrual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PotentialAccrualDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PresDirApprovalEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PresDirApprovalStartAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PresidentDirectorPjs")
                        .HasColumnType("bit");

                    b.Property<string>("PresidentDirectorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProcNum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcurementCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcurementStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProjectRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RaNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RejectionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("RejectionSymptoms")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("int");

                    b.Property<string>("SANo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SP3No")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpkNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpmpNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusAccrual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StatusBeforeRejection")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("VicePresidentPjs")
                        .HasColumnType("bit");

                    b.Property<string>("VicePresidentUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("VpApprovalEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VpApprovalStartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Wonum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProcurementId");

                    b.HasIndex("AccrualFilledByUserId");

                    b.HasIndex("AnalystHteUserId");

                    b.HasIndex("ApInvoiceUserId");

                    b.HasIndex("AppoUserId");

                    b.HasIndex("ApprovalSentByUserId");

                    b.HasIndex("ArUserId");

                    b.HasIndex("AssistantManagerUserId");

                    b.HasIndex("HardcopySubmittedByUserId");

                    b.HasIndex("IspaSubmittedByUserId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("OperationDirectorUserId");

                    b.HasIndex("PicOpsUserId");

                    b.HasIndex("PoSubmittedByUserId");

                    b.HasIndex("PrId");

                    b.HasIndex("PresidentDirectorUserId");

                    b.HasIndex("ProcNum")
                        .IsUnique()
                        .HasDatabaseName("AK_Procurements_ProcNum")
                        .HasFilter("[IsDeleted] = 0 AND [ProcNum] IS NOT NULL");

                    b.HasIndex("RejectedByUserId");

                    b.HasIndex("ResubmittedByUserId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VicePresidentUserId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Procurements_UserId_CreatedAt");

                    b.ToTable("Procurements");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcurementStatusHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ProcurementId");

                    b.HasIndex("ProcurementId", "ChangedAt");

                    b.ToTable("ProcurementStatusHistories");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProfitLoss", b =>
                {
                    b.Property<string>("ProfitLossId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("AccrualAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("DurasiTotal")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NoLetterSelectedVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProfitPercent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("RealizationAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SelectedVendorFinalOffer")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SelectedVendorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("TglMulaiMoving")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TglMulaiSewa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProfitLossId");

                    b.HasIndex("ProcurementId");

                    b.HasIndex("SelectedVendorId");

                    b.ToTable("ProfitLosses");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProfitLossItem", b =>
                {
                    b.Property<string>("ProfitLossItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("KmPer25")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("OperatorCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProcOfferId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfitLossId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal?>("TarifAdd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UnitQty")
                        .HasColumnType("int");

                    b.Property<string>("UnitTypeId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProfitLossItemId");

                    b.HasIndex("ProcOfferId");

                    b.HasIndex("ProfitLossId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("ProfitLossItems");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProfitLossSelectedVendor", b =>
                {
                    b.Property<string>("ProfitLossSelectedVendorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfitLossId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProfitLossSelectedVendorId");

                    b.HasIndex("ProcurementId");

                    b.HasIndex("ProfitLossId");

                    b.HasIndex("VendorId");

                    b.ToTable("ProfitLossSelectedVendors");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.PurchaseRequisition", b =>
                {
                    b.Property<string>("PrId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalSentByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovalTokenGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("DocumentFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("HardcopyEvidenceContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HardcopyEvidenceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HardcopyEvidenceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("HardcopyEvidenceFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("HardcopySubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HardcopySubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IspaNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("IspaSubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IspaSubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PoSubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoSubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RejectionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PrId");

                    b.HasIndex("ApprovalSentByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HardcopySubmittedByUserId");

                    b.HasIndex("IspaSubmittedByUserId");

                    b.HasIndex("PoSubmittedByUserId");

                    b.HasIndex("PrNumber")
                        .IsUnique()
                        .HasDatabaseName("AK_PurchaseRequisitions_PrNumber")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("RejectedByUserId");

                    b.ToTable("PurchaseRequisitions");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.PurchaseRequisitionStatusHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PrId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("PrId");

                    b.ToTable("PurchaseRequisitionStatusHistories");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UnitType", b =>
                {
                    b.Property<string>("UnitTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("UnitTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            UnitTypeId = "11111111-1111-1111-1111-111111111111",
                            Code = "HARI",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Hari",
                            SortOrder = 1
                        },
                        new
                        {
                            UnitTypeId = "22222222-2222-2222-2222-222222222222",
                            Code = "JAM",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Jam",
                            SortOrder = 2
                        },
                        new
                        {
                            UnitTypeId = "33333333-3333-3333-3333-333333333333",
                            Code = "LSP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Lumpsum",
                            SortOrder = 3
                        },
                        new
                        {
                            UnitTypeId = "44444444-4444-4444-4444-444444444444",
                            Code = "TRIP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Trip",
                            SortOrder = 4
                        },
                        new
                        {
                            UnitTypeId = "55555555-5555-5555-5555-555555555555",
                            Code = "KALI",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Kali",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarFileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AvatarObjectKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("AvatarUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONCAT([FirstName], ' ', [LastName])");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RecoveryCodesGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RecoveryCodesHidden")
                        .HasColumnType("bit");

                    b.Property<string>("RecoveryCodesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("TwoFactorMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("None");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UserSecurityLog", b =>
                {
                    b.Property<string>("UserSecurityLogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserSecurityLogId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSecurityLogs");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UserSession", b =>
                {
                    b.Property<string>("UserSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Browser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Device")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Vendor", b =>
                {
                    b.Property<string>("VendorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NPWP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.HasIndex("VendorCode")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.VendorOffer", b =>
                {
                    b.Property<string>("VendorOfferId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NoLetter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProcOfferId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfitLossId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantityItem")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOfUnit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("UnitTypeId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VendorOfferId");

                    b.HasIndex("ProcOfferId");

                    b.HasIndex("ProcurementId");

                    b.HasIndex("ProfitLossId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorOffers");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.VendorRoundLetter", b =>
                {
                    b.Property<string>("VendorRoundLetterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LetterNumber")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProcDocumentId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProcurementId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfitLossId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VendorRoundLetterId");

                    b.HasIndex("ProcDocumentId");

                    b.HasIndex("VendorId");

                    b.HasIndex("ProcurementId", "VendorId", "Round")
                        .IsUnique();

                    b.ToTable("VendorRoundLetters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.DocumentApprovalRule", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId");

                    b.HasOne("ProcurementHTE.Core.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.JobTypes", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "SubmitterUser")
                        .WithMany()
                        .HasForeignKey("SubmitterUserId");

                    b.Navigation("ApproverUser");

                    b.Navigation("DocumentType");

                    b.Navigation("JobType");

                    b.Navigation("SubmitterUser");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.DocumentApprovals", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.JobTypeDocuments", "JobTypeDocument")
                        .WithMany("DocumentApprovals")
                        .HasForeignKey("JobTypeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTypeDocument");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.JobTypeDocuments", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.DocumentType", "DocumentType")
                        .WithMany("JobTypeDocuments")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.JobTypes", "JobType")
                        .WithMany("JobTypeDocuments")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Notification", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcDetail", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.Procurement", "Procurement")
                        .WithMany("ProcDetails")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Procurement");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcDocuments", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.DocumentType", "DocumentType")
                        .WithMany("ProcDocuments")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.Procurement", "Procurement")
                        .WithMany("ProcDocuments")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcOffer", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.Procurement", "Procurement")
                        .WithMany("ProcOffers")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Procurement", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "AccrualFilledByUser")
                        .WithMany()
                        .HasForeignKey("AccrualFilledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProcurementHTE.Core.Models.User", "AnalystHteUser")
                        .WithMany()
                        .HasForeignKey("AnalystHteUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "ApInvoiceUser")
                        .WithMany()
                        .HasForeignKey("ApInvoiceUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "AppoUser")
                        .WithMany()
                        .HasForeignKey("AppoUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "ApprovalSentByUser")
                        .WithMany()
                        .HasForeignKey("ApprovalSentByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "ArUser")
                        .WithMany()
                        .HasForeignKey("ArUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "AssistantManagerUser")
                        .WithMany()
                        .HasForeignKey("AssistantManagerUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "HardcopySubmittedByUser")
                        .WithMany()
                        .HasForeignKey("HardcopySubmittedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "IspaSubmittedByUser")
                        .WithMany()
                        .HasForeignKey("IspaSubmittedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.JobTypes", "JobType")
                        .WithMany("Procurements")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "ManagerUser")
                        .WithMany()
                        .HasForeignKey("ManagerUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "OperationDirectorUser")
                        .WithMany()
                        .HasForeignKey("OperationDirectorUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "PicOpsUser")
                        .WithMany()
                        .HasForeignKey("PicOpsUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "PoSubmittedByUser")
                        .WithMany()
                        .HasForeignKey("PoSubmittedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.PurchaseRequisition", "PurchaseRequisition")
                        .WithMany("Procurements")
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProcurementHTE.Core.Models.User", "PresidentDirectorUser")
                        .WithMany()
                        .HasForeignKey("PresidentDirectorUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "RejectedByUser")
                        .WithMany()
                        .HasForeignKey("RejectedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.User", "ResubmittedByUser")
                        .WithMany()
                        .HasForeignKey("ResubmittedByUserId");

                    b.HasOne("ProcurementHTE.Core.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.User", "User")
                        .WithMany("Procurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProcurementHTE.Core.Models.User", "VicePresidentUser")
                        .WithMany()
                        .HasForeignKey("VicePresidentUserId");

                    b.Navigation("AccrualFilledByUser");

                    b.Navigation("AnalystHteUser");

                    b.Navigation("ApInvoiceUser");

                    b.Navigation("AppoUser");

                    b.Navigation("ApprovalSentByUser");

                    b.Navigation("ArUser");

                    b.Navigation("AssistantManagerUser");

                    b.Navigation("HardcopySubmittedByUser");

                    b.Navigation("IspaSubmittedByUser");

                    b.Navigation("JobType");

                    b.Navigation("ManagerUser");

                    b.Navigation("OperationDirectorUser");

                    b.Navigation("PicOpsUser");

                    b.Navigation("PoSubmittedByUser");

                    b.Navigation("PresidentDirectorUser");

                    b.Navigation("PurchaseRequisition");

                    b.Navigation("RejectedByUser");

                    b.Navigation("ResubmittedByUser");

                    b.Navigation("Status");

                    b.Navigation("User");

                    b.Navigation("VicePresidentUser");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProcurementStatusHistory", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProcurementHTE.Core.Models.Procurement", "Procurement")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProfitLoss", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.Procurement", "Procurement")
                        .WithMany("ProfitLosses")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.Vendor", "SelectedVendor")
                        .WithMany()
                        .HasForeignKey("SelectedVendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procurement");

                    b.Navigation("SelectedVendor");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProfitLossItem", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.ProcOffer", "ProcOffer")
                        .WithMany()
                        .HasForeignKey("ProcOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.ProfitLoss", "ProfitLoss")
                        .WithMany("Items")
                        .HasForeignKey("ProfitLossId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.UnitType", "UnitType")
                        .WithMany("ProfitLossItems")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcOffer");

                    b.Navigation("ProfitLoss");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProfitLossSelectedVendor", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.Procurement", "Procurement")
                        .WithMany()
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.ProfitLoss", "ProfitLoss")
                        .WithMany("VendorList")
                        .HasForeignKey("ProfitLossId");

                    b.HasOne("ProcurementHTE.Core.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procurement");

                    b.Navigation("ProfitLoss");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.PurchaseRequisition", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "ApprovalSentByUser")
                        .WithMany()
                        .HasForeignKey("ApprovalSentByUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.User", "HardcopySubmittedByUser")
                        .WithMany()
                        .HasForeignKey("HardcopySubmittedByUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "IspaSubmittedByUser")
                        .WithMany()
                        .HasForeignKey("IspaSubmittedByUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "PoSubmittedByUser")
                        .WithMany()
                        .HasForeignKey("PoSubmittedByUserId");

                    b.HasOne("ProcurementHTE.Core.Models.User", "RejectedByUser")
                        .WithMany()
                        .HasForeignKey("RejectedByUserId");

                    b.Navigation("ApprovalSentByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("HardcopySubmittedByUser");

                    b.Navigation("IspaSubmittedByUser");

                    b.Navigation("PoSubmittedByUser");

                    b.Navigation("RejectedByUser");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.PurchaseRequisitionStatusHistory", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId");

                    b.HasOne("ProcurementHTE.Core.Models.PurchaseRequisition", "PurchaseRequisition")
                        .WithMany("StatusHistories")
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("PurchaseRequisition");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UserRole", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UserSecurityLog", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "User")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UserSession", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.VendorOffer", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.ProcOffer", "ProcOffer")
                        .WithMany()
                        .HasForeignKey("ProcOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.Procurement", "Procurement")
                        .WithMany("VendorOffers")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.ProfitLoss", "ProfitLoss")
                        .WithMany("VendorOffers")
                        .HasForeignKey("ProfitLossId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.UnitType", "UnitType")
                        .WithMany("VendorOffers")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.Vendor", "Vendor")
                        .WithMany("VendorOffers")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcOffer");

                    b.Navigation("Procurement");

                    b.Navigation("ProfitLoss");

                    b.Navigation("UnitType");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.VendorRoundLetter", b =>
                {
                    b.HasOne("ProcurementHTE.Core.Models.ProcDocuments", "ProcDocument")
                        .WithMany()
                        .HasForeignKey("ProcDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementHTE.Core.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcDocument");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.DocumentType", b =>
                {
                    b.Navigation("JobTypeDocuments");

                    b.Navigation("ProcDocuments");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.JobTypeDocuments", b =>
                {
                    b.Navigation("DocumentApprovals");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.JobTypes", b =>
                {
                    b.Navigation("JobTypeDocuments");

                    b.Navigation("Procurements");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Procurement", b =>
                {
                    b.Navigation("ProcDetails");

                    b.Navigation("ProcDocuments");

                    b.Navigation("ProcOffers");

                    b.Navigation("ProfitLosses");

                    b.Navigation("StatusHistories");

                    b.Navigation("VendorOffers");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.ProfitLoss", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("VendorList");

                    b.Navigation("VendorOffers");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.PurchaseRequisition", b =>
                {
                    b.Navigation("Procurements");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.UnitType", b =>
                {
                    b.Navigation("ProfitLossItems");

                    b.Navigation("VendorOffers");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.User", b =>
                {
                    b.Navigation("Procurements");

                    b.Navigation("SecurityLogs");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ProcurementHTE.Core.Models.Vendor", b =>
                {
                    b.Navigation("VendorOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
